In [1]:
import gradio as gr
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
from PIL import Image, ImageOps

# Load model (assuming the path is correct)
model = load_model('./checkpoints/checkpoints_ours_2/weights.1716893020.hdf5')

# Define class labels
class_labels = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
                'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']


def classify_image(image):
    """Preprocesses the image and predicts the class using the loaded model."""
    data_list = list(image.values())[0]  # Extract values as a list of lists
    image = np.array(data_list).astype(np.uint8)  # Convert to uint8
    print("Shape before processing:", image.shape)

    # Visualize the raw image data
    plt.imshow(image, cmap='gray')
    plt.show()

    # Convert to PIL Image
    image = Image.fromarray(image).convert('L')  # Convert to grayscale PIL Image
    image = ImageOps.invert(image)  # Invert colors
    image = image.resize((28, 28))  # Resize to 28x28 (model's expected size)
    # Prepare the image for the model
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    image /= 255.0  # Normalize pixel values
    print("Shape after processing:", image.shape)

    # Predict the class
    prediction = model.predict(image)
    predicted_index = np.argmax(prediction)
    predicted_class = class_labels[predicted_index]

    return predicted_class, image


# Create Gradio interface with drawing capabilities
interface = gr.Interface(
    fn=classify_image,
    inputs="sketchpad",
    outputs=[gr.Label(num_top_classes=1), gr.Image()],
    title="EMNIST image classification",
    description="Draw a character on the canvas. The model will predict what it is!"
)

# Launch the interface
interface.launch(share=True)  # Open in a new web browser window

2024-06-12 19:59:02.357857: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-12 19:59:02.357898: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-12 19:59:02.357934: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-12 19:59:02.364724: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-12 19:59:03.038192: W tensorflow/compiler/

Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://b9fe3e580ef87b1b29.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


: 

In [19]:
def classify_image(image):
    """Preprocesses the image and predicts the class using the loaded model."""
    data_list = list(image.values())[0]  # Extract values as a list of lists
    image = np.array(data_list).astype(np.uint8)  # Convert to uint8
    print("Shape before processing:", image.shape)

    # Visualize the raw image data
    plt.imshow(image, cmap='gray')
    plt.show()

    # Convert to PIL Image
    image = Image.fromarray(image).convert('L')  # Convert to grayscale PIL Image
    image = ImageOps.invert(image)  # Invert colors
    image = image.resize((28, 28))  # Resize to 28x28 (model's expected size)
    # Prepare the image for the model
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    image /= 255.0  # Normalize pixel values
    print("Shape after processing:", image.shape)

    # Predict the class
    prediction = model.predict(image)
    predicted_index = np.argmax(prediction)
    predicted_class = class_labels[predicted_index]

    # Convert processed image for display
    display_image = np.squeeze(image) * 255  # Scale back to 0-255 range
    display_image = display_image.astype(np.uint8)  # Convert to uint8
    # Convert grayscale to RGB for compatibility
    display_image = np.stack((display_image,)*3, axis=-1)

    return predicted_class, display_image

# Create Gradio interface with drawing capabilities
interface = gr.Interface(
    fn=classify_image,
    inputs="sketchpad",
    outputs=[gr.Label(num_top_classes=1), gr.Image()],
    title="EMNIST image classification",
    description="Draw a character on the canvas. The model will predict what it is and show the processed image!"
)

# Launch the interface
interface.launch(share=True)  # Open in a new web browser window


Running on local URL:  http://127.0.0.1:7873
Running on public URL: https://e24daab0f4dd2f072e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


Shape before processing: (600, 800, 4)
Shape after processing: (1, 28, 28, 1)
1/1 [==============================] - 0s 175ms/step


In [23]:
import gradio as gr
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
from PIL import Image, ImageOps

# Load model (assuming the path is correct)
model = load_model('./checkpoints/checkpoints_ours_2/weights.1716893020.hdf5')

# Define class labels
class_labels = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
                'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']


def classify_image(image):
    """Preprocesses the image and predicts the class using the loaded model."""
    data_list = list(image.values())[0]
    image = np.array(data_list).astype(np.uint8)
    print("Data values (unique):", np.unique(image))  # 고유 값 출력
    print("Data values (min, max):", image.min(), image.max())
    print("Shape before processing:", image.shape)

    # Visualize the raw image data
    plt.imshow(image, cmap='gray')
    plt.show()
    
    plt.imshow(image, cmap='gray', vmin=0, vmax=255)
    plt.colorbar()
    plt.title("Input Image")
    plt.show()

    # Convert to PIL Image
    image = Image.fromarray(image).convert('L')  # Convert to grayscale PIL Image
    image = ImageOps.invert(image)  # Invert colors
    image = image.resize((28, 28))  # Resize to 28x28 (model's expected size)
    # Prepare the image for the model
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    image /= 255.0  # Normalize pixel values
    print("Shape after processing:", image.shape)

    # Predict the class
    prediction = model.predict(image)
    predicted_index = np.argmax(prediction)
    predicted_class = class_labels[predicted_index]

    return predicted_class, image


# Create Gradio interface with drawing capabilities
interface = gr.Interface(
    fn=classify_image,
    inputs="sketchpad",
    outputs=[gr.Label(num_top_classes=1),gr.Image()],
    title="EMNIST image classification",
    description="Draw a character on the canvas. The model will predict what it is!"
)

# Launch the interface
interface.launch(share=True)  # Open in a new web browser window

Running on local URL:  http://127.0.0.1:7877
Running on public URL: https://1fe7f74db997ad526a.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


Data values (unique): [0]
Data values (min, max): 0 0
Shape before processing: (600, 800, 4)
Shape after processing: (1, 28, 28, 1)
1/1 [==============================] - 0s 152ms/step


Traceback (most recent call last):
  File "/home/suhohan/anaconda3/envs/ann/lib/python3.10/site-packages/PIL/Image.py", line 3130, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 28, 1), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suhohan/anaconda3/envs/ann/lib/python3.10/site-packages/gradio/queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "/home/suhohan/anaconda3/envs/ann/lib/python3.10/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/suhohan/anaconda3/envs/ann/lib/python3.10/site-packages/gradio/blocks.py", line 1918, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/suhohan/anaconda3/envs/ann/lib/python3.10/site-packages/gradio/blocks.py", line 1744, in postprocess_data
    predictio

In [36]:
!pip install skimage

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      
      *** Please install the `scikit-image` package (instead of `skimage`) ***
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [44]:
import os
import gradio as gr
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
from skimage.transform import resize
from PIL import Image, ImageOps

os.environ["CUDA_VISIBLE_DEVICES"]="2"

# Load model (assuming the path is correct)
model = load_model('./checkpoints/checkpoints_ours_2/weights.1716893020.hdf5')

# Define class labels
class_labels = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
                'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

def classify_image(image):
    """Preprocesses the image and predicts the class using the loaded model."""
    print(image.keys())
    image_ = image['composite']
    print(image_)

    # data_list = list(image_)[0]
    image = np.array(image_).astype(np.uint8)
    print("Data values (unique):", np.unique(image))  # 고유 값 출력
    print("Data values (min, max):", image.min(), image.max())
    print("Shape before processing:", image.shape)
    
    # image=image[:,:,0]

    # # Convert to PIL Image
    # # image = Image.fromarray(image).convert('L')  # Convert to grayscale PIL Image
    # image = Image.fromarray(image)
    # image = ImageOps.invert(image)  # Invert colors
    # # image_1 = img_to_array(image)
    # # print("Data values (unique):", np.unique(image_1))  # 고유 값 출력

    # image = image.resize((28, 28))  # Resize to 28x28 (model's expected size)
    
    # Prepare the image for the model
    # image = img_to_array(image)
    # 색상 반전 (255 - pixel value)
    inverted_image = 255 - image[:,:,0]  # 채널을 선택하고 반전
    print("Data values (unique):", np.unique(image))  # 고유 값 출력
    print("After inversion - Min and max values:", inverted_image.min(), inverted_image.max())
    print("Data values (unique):", np.unique(image))  # 고유 값 출력

    # 이미지 크기 조정
    resized_image = resize(inverted_image, (28, 28), mode='reflect', anti_aliasing=True)
    print("Shape after resizing:", resized_image.shape)


    # 결과 이미지는 (28, 28)이지만, 모델 입력에 맞게 차원을 추가 (28, 28, 1)
    resized_image = resized_image.reshape((28, 28, 1))
    
    image = np.expand_dims(resized_image, axis=0)  # Add batch dimension
    print("Shape after processing:", image.shape)
    print("Data values (unique):", np.unique(image))  # 고유 값 출력
    for i in range(28):
        print(image[0,:,i,0])
        

    # Predict the class
    prediction = model.predict(image)
    predicted_index = np.argmax(prediction)
    predicted_class = class_labels[predicted_index]

    # Convert processed image for display
    display_image = np.squeeze(image)  # Rescale back to 0-255 range
    display_image = display_image.astype(np.uint8)  # Ensure type is uint8
    display_image = Image.fromarray(display_image)  # Convert numpy array back to PIL Image for display

    return predicted_class, display_image

# Create Gradio interface with drawing capabilities
interface = gr.Interface(
    fn=classify_image,
    inputs="sketchpad",
    outputs=[gr.Label(num_top_classes=1), gr.Image()],
    title="EMNIST image classification",
    description="Draw a character on the canvas. The model will predict what it is!"
)

# Launch the interface
interface.launch(share=True)


Running on local URL:  http://127.0.0.1:7888
Running on public URL: https://35c59a17ee6ac0ba2e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


dict_keys(['background', 'layers', 'composite'])
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Data values (unique): [  0 255]
Data values (min, max): 0 255
Shape before processing: (600, 800, 4)
Data values (unique): [  0 255]
After inversion - Min and max values: 255 255
Data values (unique): [  0 255]
Shape after resizing: (28, 28)
Shape after processing: (1, 28, 28, 1)
Data values (unique): [1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

: 

In [23]:
from PIL import Image
import numpy as np

def print_image_info(image_path):
    # 이미지 파일 불러오기
    image = Image.open(image_path)
    
    # 이미지를 NumPy 배열로 변환
    image_array = np.array(image)
    
    # 이미지 데이터 출력
    print("Image data (array):")
    print(image_array)
    
    # 이미지 shape 출력
    print("Image shape:", image_array.shape)
    
    # 이미지 데이터 유형과 최소값, 최대값 출력
    print("Data type:", image_array.dtype)
    print("Min pixel value:", image_array.min())
    print("Max pixel tile value:", image_array.max())
    
    # 고유한 픽셀 값 출력
    unique_values = np.unique(image_array)
    print("Unique pixel values:", unique_values)
    
    # 이미지 시각화
    image.show()

# PNG 파일 경로 지정
image_path = '/home/suhohan/ann-project/flagged/image/c0684eb3f9026a6bc31e/composite.png'

# 함수 호출
print_image_info(image_path)


Image data (array):
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Image shape: (600, 800, 4)
Data type: uint8
Min pixel value: 0
Max pixel tile value: 255
Unique pixel values: [  0 255]


Error: no "view" rule for type "image/png" passed its test case
       (for more information, add "--debug=1" on the command line)


dict_keys(['background', 'layers', 'composite'])
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Data values (unique): [  0 255]
Data values (min, max): 0 255
Shape before processing: (600, 800, 4)
Shape after processing: (1, 28, 28, 1)
1/1 [==============================] - 0s 163ms/step
